#ifndef BANKSIMUL_DATABASELIB_GLOBAL_H
#define BANKSIMUL_DATABASELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BANKSIMUL_DATABASELIB_LIBRARY)
#  define BANKSIMUL_DATABASELIB_EXPORT Q_DECL_EXPORT
#else
#  define BANKSIMUL_DATABASELIB_EXPORT Q_DECL_IMPORT
#endif

#endif // BANKSIMUL_DATABASELIB_GLOBAL_H
